### ISSUE TITLE
[Question] How to make payment using authorize request?

### ISSUE THREAD

**Issue by morcano** [Dewbud/CardConnect#15]
Hey guys! I'm a little confused about how can I make a payment. I'm using [Hosted iFrame Tokenizer](https://developer.cardconnect.com/hosted-iframe-tokenizer) for tokenize card data from my front end, and this is a request from backend side:
```
$test = new CardConnect\CardPointe('prod_merchant', 'prod_login', 'prod_password', 'https://fts.cardconnect.com/');

        $request = new CardConnect\Requests\AuthorizationRequest([
            'account'  => $request->cc_token, // card token from Hosted iFrame Tokenizer
            'amount'   => $request->amount,  // 123
            'expiry'     =>  $request->cc_expiry, // YYYYMM
            'currency' => 'USD'
        ]);

        $response = $test->authorize($request); 
```
When I'm trying to debug response, I see:
```
Dewbud\CardConnect\Responses\CaptureResponse {#666
  #_numericFields: array:1 [
    0 => "amount"
  ]
  #attributes: array:12 [
    "respproc" => "PPS"
    "amount" => 0
    "resptext" => "Invalid token" <<< ???
    "cardproc" => "RPCT"
    "commcard" => "N"
    "expiry" => "1024"
    "retref" => "713802061924"
    "respstat" => "C"
    "respcode" => "98"
    "account" => "XXXXXXXXXXXXX"
    "merchid" => "XXXXXXXXXXXXX"
    "token" => "XXXXXXXXXXXXX"
  ]
}
```

Btw, that doesn't happen when I'm trying to make request with a test card to test environment... 
What am I doing wrong?

**Comment by Dewbud** [comment]
I would suggest looking at through the chain of requests/responses that lead up to the authorization.
It's possible the `cc_token` is getting mangled somewhere along the way.
Look at the response in the browser from the tokenizer, then the request that gets sent to the server and then the request that gets dispatched to the gateway. Make sure the `cc_token` matches on each step.

The `last_request` attribute on the client will contain the body of the request that is actually dispatched on the server, if that's helpful in your debugging.

**Comment by aaronbauman** [comment]
I'm looking at implementing something similar. @morcano did you get this working?
