### ISSUE TITLE
Profile Service Issue

### ISSUE THREAD

**Issue by raghavdm** [Dewbud/CardConnect#2]
Hi, thanks for quick update.

There are some errors while sending request to card connect for GET and DELETE profile request. Please change the code on line 280 with this:

> $res = $this->send('GET', "profile/$profile_id/$account_id/{$this->merchant_id}", null);

and on line 297 with

> $res = $this->send('DELETE', "profile/$profile_id/$account_id/{$this->merchant_id}", null);

and also add this code in createProfile

> $params = [
>            'merchid'  => $this->merchant_id
> ];
> $request = array_merge($params, $request);

**Comment by Dewbud** [comment]
Hi @raghavdm,

I have added the changes you suggested to the `profile` and `deleteProfile` methods
In the future please submit a pull request as it's easier to see the changes you're requesting.

@lkagan addressed your request for defaulting the 'merchid' param in the `createProfile` method with his PR https://github.com/Dewbud/CardConnect/pull/3
