### ISSUE TITLE
Packagist not picking up new releases

### ISSUE THREAD

**Issue by pmccarren** [Dewbud/CardConnect#4]
Hello!

Packagist is not importing new releases. The most recent release in packagist is `1.0.2`, which is a few releases behind `1.0.5` which is the latest as of now.

https://packagist.org/packages/dewbud/cardconnect

Happy to help in any way I can!

**Comment by Dewbud** [comment]
Thanks for letting me know, client version is now 1.1.0 and packagist is now syncing correctly
