### ISSUE TITLE
UAT Testing URL

### ISSUE THREAD

**Issue by rodruiz** [Dewbud/CardConnect#7]
Hi,
following the [CardPointe documentation](https://developer.cardconnect.com/guides/cardpointe-gateway#understanding-the-uat-environment)
CardConnect provides a sandbox UAT environment for integration testing. Your application can target this environment at **https://fts-uat.cardconnect.com**

But in the [tests](https://github.com/Dewbud/CardConnect/blob/master/tests/Feature/CardPointeTest.php#L19) you are using:
```php
const SERVER   = 'https://fts.cardconnect.com:6443/';
```

You should use the following right?
```php
const SERVER   = 'https://fts-uat.cardconnect.com/';
```

Thanks

**Comment by Dewbud** [comment]
It's very possible, I haven't personally used this processor for some time.

If there is anything you see that has changed in the API since I first implemented this you're more than welcome to submit a PR to help maintain this tool for others.

**Comment by rodruiz** [comment]
I'll submit a PR very soon.
Are you ok if we upgrade to php 7?

**Comment by Dewbud** [comment]
Should be fine, I'll just mark it as a major release to keep semantic versioning
